//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication3.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:dajana", ConfigurationName="ServiceReference1.zeiterfassungPortType")]
    public interface zeiterfassungPortType {
        
        // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Wrappernamespace () von Nachricht "checkLoginRequest" nicht mit dem Standardwert (urn:dajana) übereinstimmt.
        [System.ServiceModel.OperationContractAttribute(Action="http://193.196.143.148/soap/index.php/checkLogin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WpfApplication3.ServiceReference1.checkLoginResponse checkLogin(WpfApplication3.ServiceReference1.checkLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://193.196.143.148/soap/index.php/checkLogin", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.checkLoginResponse> checkLoginAsync(WpfApplication3.ServiceReference1.checkLoginRequest request);
        
        // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Wrappernamespace () von Nachricht "createprojectRequest" nicht mit dem Standardwert (urn:dajana) übereinstimmt.
        [System.ServiceModel.OperationContractAttribute(Action="http://193.196.143.148/soap/index.php/createproject", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WpfApplication3.ServiceReference1.createprojectResponse createproject(WpfApplication3.ServiceReference1.createprojectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://193.196.143.148/soap/index.php/createproject", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.createprojectResponse> createprojectAsync(WpfApplication3.ServiceReference1.createprojectRequest request);
        
        // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Wrappernamespace () von Nachricht "selectedcustomerRequest" nicht mit dem Standardwert (urn:dajana) übereinstimmt.
        [System.ServiceModel.OperationContractAttribute(Action="http://193.196.143.148/soap/index.php/selectedcustomer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WpfApplication3.ServiceReference1.selectedcustomerResponse selectedcustomer(WpfApplication3.ServiceReference1.selectedcustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://193.196.143.148/soap/index.php/selectedcustomer", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.selectedcustomerResponse> selectedcustomerAsync(WpfApplication3.ServiceReference1.selectedcustomerRequest request);
        
        // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Wrappernamespace () von Nachricht "createcustomerRequest" nicht mit dem Standardwert (urn:dajana) übereinstimmt.
        [System.ServiceModel.OperationContractAttribute(Action="http://193.196.143.148/soap/index.php/createcustomer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WpfApplication3.ServiceReference1.createcustomerResponse createcustomer(WpfApplication3.ServiceReference1.createcustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://193.196.143.148/soap/index.php/createcustomer", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.createcustomerResponse> createcustomerAsync(WpfApplication3.ServiceReference1.createcustomerRequest request);
        
        // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Wrappernamespace () von Nachricht "createemployeeRequest" nicht mit dem Standardwert (urn:dajana) übereinstimmt.
        [System.ServiceModel.OperationContractAttribute(Action="http://193.196.143.148/soap/index.php/createemployee", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WpfApplication3.ServiceReference1.createemployeeResponse createemployee(WpfApplication3.ServiceReference1.createemployeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://193.196.143.148/soap/index.php/createemployee", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.createemployeeResponse> createemployeeAsync(WpfApplication3.ServiceReference1.createemployeeRequest request);
        
        // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Wrappernamespace () von Nachricht "customerhasaddressRequest" nicht mit dem Standardwert (urn:dajana) übereinstimmt.
        [System.ServiceModel.OperationContractAttribute(Action="http://193.196.143.148/soap/index.php/customerhasaddress", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WpfApplication3.ServiceReference1.customerhasaddressResponse customerhasaddress(WpfApplication3.ServiceReference1.customerhasaddressRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://193.196.143.148/soap/index.php/customerhasaddress", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.customerhasaddressResponse> customerhasaddressAsync(WpfApplication3.ServiceReference1.customerhasaddressRequest request);
        
        // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Wrappernamespace () von Nachricht "employeehasaddressRequest" nicht mit dem Standardwert (urn:dajana) übereinstimmt.
        [System.ServiceModel.OperationContractAttribute(Action="http://193.196.143.148/soap/index.php/employeehasaddress", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WpfApplication3.ServiceReference1.employeehasaddressResponse employeehasaddress(WpfApplication3.ServiceReference1.employeehasaddressRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://193.196.143.148/soap/index.php/employeehasaddress", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.employeehasaddressResponse> employeehasaddressAsync(WpfApplication3.ServiceReference1.employeehasaddressRequest request);
        
        // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Wrappernamespace () von Nachricht "createaddressRequest" nicht mit dem Standardwert (urn:dajana) übereinstimmt.
        [System.ServiceModel.OperationContractAttribute(Action="http://193.196.143.148/soap/index.php/createaddress", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WpfApplication3.ServiceReference1.createaddressResponse createaddress(WpfApplication3.ServiceReference1.createaddressRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://193.196.143.148/soap/index.php/createaddress", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.createaddressResponse> createaddressAsync(WpfApplication3.ServiceReference1.createaddressRequest request);
        
        // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Wrappernamespace () von Nachricht "startWorkRequest" nicht mit dem Standardwert (urn:dajana) übereinstimmt.
        [System.ServiceModel.OperationContractAttribute(Action="http://193.196.143.148/soap/index.php/startWork", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WpfApplication3.ServiceReference1.startWorkResponse startWork(WpfApplication3.ServiceReference1.startWorkRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://193.196.143.148/soap/index.php/startWork", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.startWorkResponse> startWorkAsync(WpfApplication3.ServiceReference1.startWorkRequest request);
        
        // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Wrappernamespace () von Nachricht "stopWorkRequest" nicht mit dem Standardwert (urn:dajana) übereinstimmt.
        [System.ServiceModel.OperationContractAttribute(Action="http://193.196.143.148/soap/index.php/stopWork", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WpfApplication3.ServiceReference1.stopWorkResponse stopWork(WpfApplication3.ServiceReference1.stopWorkRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://193.196.143.148/soap/index.php/stopWork", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.stopWorkResponse> stopWorkAsync(WpfApplication3.ServiceReference1.stopWorkRequest request);
        
        // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Wrappernamespace () von Nachricht "pauseWorkRequest" nicht mit dem Standardwert (urn:dajana) übereinstimmt.
        [System.ServiceModel.OperationContractAttribute(Action="http://193.196.143.148/soap/index.php/pauseWork", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WpfApplication3.ServiceReference1.pauseWorkResponse pauseWork(WpfApplication3.ServiceReference1.pauseWorkRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://193.196.143.148/soap/index.php/pauseWork", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.pauseWorkResponse> pauseWorkAsync(WpfApplication3.ServiceReference1.pauseWorkRequest request);
        
        // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Wrappernamespace () von Nachricht "stopPauseWorkRequest" nicht mit dem Standardwert (urn:dajana) übereinstimmt.
        [System.ServiceModel.OperationContractAttribute(Action="http://193.196.143.148/soap/index.php/stopPauseWork", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WpfApplication3.ServiceReference1.stopPauseWorkResponse stopPauseWork(WpfApplication3.ServiceReference1.stopPauseWorkRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://193.196.143.148/soap/index.php/stopPauseWork", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.stopPauseWorkResponse> stopPauseWorkAsync(WpfApplication3.ServiceReference1.stopPauseWorkRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="rpc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string[] loadprojects();
        
        [System.ServiceModel.OperationContractAttribute(Action="rpc", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string[]> loadprojectsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="rpc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string[] loadcustomers();
        
        [System.ServiceModel.OperationContractAttribute(Action="rpc", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string[]> loadcustomersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="rpc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string[] loadactivities();
        
        [System.ServiceModel.OperationContractAttribute(Action="rpc", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string[]> loadactivitiesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="rpc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string[] loadauthorisations();
        
        [System.ServiceModel.OperationContractAttribute(Action="rpc", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string[]> loadauthorisationsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="rpc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TableDataActivities))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TableDataProjects))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TableDataEmployees))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TableDataCustomers))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TableDataWorkingTimes))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WpfApplication3.ServiceReference1.TableDataWorkingTimes[] loadtableworkingtimes();
        
        [System.ServiceModel.OperationContractAttribute(Action="rpc", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.TableDataWorkingTimes[]> loadtableworkingtimesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="rpc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TableDataActivities))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TableDataProjects))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TableDataEmployees))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TableDataCustomers))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TableDataWorkingTimes))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WpfApplication3.ServiceReference1.TableDataCustomers[] loadtablecustomers();
        
        [System.ServiceModel.OperationContractAttribute(Action="rpc", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.TableDataCustomers[]> loadtablecustomersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="rpc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TableDataActivities))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TableDataProjects))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TableDataEmployees))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TableDataCustomers))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TableDataWorkingTimes))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WpfApplication3.ServiceReference1.TableDataEmployees[] loadtableemployees();
        
        [System.ServiceModel.OperationContractAttribute(Action="rpc", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.TableDataEmployees[]> loadtableemployeesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="rpc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TableDataActivities))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TableDataProjects))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TableDataEmployees))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TableDataCustomers))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TableDataWorkingTimes))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WpfApplication3.ServiceReference1.TableDataProjects[] loadtableprojects();
        
        [System.ServiceModel.OperationContractAttribute(Action="rpc", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.TableDataProjects[]> loadtableprojectsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="rpc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TableDataActivities))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TableDataProjects))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TableDataEmployees))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TableDataCustomers))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TableDataWorkingTimes))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WpfApplication3.ServiceReference1.TableDataActivities[] loadtableactivities();
        
        [System.ServiceModel.OperationContractAttribute(Action="rpc", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.TableDataActivities[]> loadtableactivitiesAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="checkLogin", WrapperNamespace="", IsWrapped=true)]
    public partial class checkLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string persnr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int pin;
        
        public checkLoginRequest() {
        }
        
        public checkLoginRequest(string persnr, int pin) {
            this.persnr = persnr;
            this.pin = pin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="checkLoginResponse", WrapperNamespace="", IsWrapped=true)]
    public partial class checkLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public bool @return;
        
        public checkLoginResponse() {
        }
        
        public checkLoginResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createproject", WrapperNamespace="", IsWrapped=true)]
    public partial class createprojectRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int idprojekt;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string projektname;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string projektbeschreibung;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public int status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public int kundennr;
        
        public createprojectRequest() {
        }
        
        public createprojectRequest(int idprojekt, string projektname, string projektbeschreibung, int status, int kundennr) {
            this.idprojekt = idprojekt;
            this.projektname = projektname;
            this.projektbeschreibung = projektbeschreibung;
            this.status = status;
            this.kundennr = kundennr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createprojectResponse", WrapperNamespace="", IsWrapped=true)]
    public partial class createprojectResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public createprojectResponse() {
        }
        
        public createprojectResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="selectedcustomer", WrapperNamespace="", IsWrapped=true)]
    public partial class selectedcustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Firmenname;
        
        public selectedcustomerRequest() {
        }
        
        public selectedcustomerRequest(string Firmenname) {
            this.Firmenname = Firmenname;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="selectedcustomerResponse", WrapperNamespace="", IsWrapped=true)]
    public partial class selectedcustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public selectedcustomerResponse() {
        }
        
        public selectedcustomerResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createcustomer", WrapperNamespace="", IsWrapped=true)]
    public partial class createcustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int KundenNr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Nachname;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string Vorname;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string Firmenname;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string TelNrMobil;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string TelNrFestnetz;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string EMail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public int Status;
        
        public createcustomerRequest() {
        }
        
        public createcustomerRequest(int KundenNr, string Nachname, string Vorname, string Firmenname, string TelNrMobil, string TelNrFestnetz, string EMail, int Status) {
            this.KundenNr = KundenNr;
            this.Nachname = Nachname;
            this.Vorname = Vorname;
            this.Firmenname = Firmenname;
            this.TelNrMobil = TelNrMobil;
            this.TelNrFestnetz = TelNrFestnetz;
            this.EMail = EMail;
            this.Status = Status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createcustomerResponse", WrapperNamespace="", IsWrapped=true)]
    public partial class createcustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public createcustomerResponse() {
        }
        
        public createcustomerResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createemployee", WrapperNamespace="", IsWrapped=true)]
    public partial class createemployeeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int MitarbeiterNr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Nachname;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string Vorname;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string GebTag;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string Abteilung;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string TelNrMobil;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string TelNrFestnetz;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public string EMail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
        public int Berechtigungsstufe;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=9)]
        public int PIN;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=10)]
        public bool Status;
        
        public createemployeeRequest() {
        }
        
        public createemployeeRequest(int MitarbeiterNr, string Nachname, string Vorname, string GebTag, string Abteilung, string TelNrMobil, string TelNrFestnetz, string EMail, int Berechtigungsstufe, int PIN, bool Status) {
            this.MitarbeiterNr = MitarbeiterNr;
            this.Nachname = Nachname;
            this.Vorname = Vorname;
            this.GebTag = GebTag;
            this.Abteilung = Abteilung;
            this.TelNrMobil = TelNrMobil;
            this.TelNrFestnetz = TelNrFestnetz;
            this.EMail = EMail;
            this.Berechtigungsstufe = Berechtigungsstufe;
            this.PIN = PIN;
            this.Status = Status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createemployeeResponse", WrapperNamespace="", IsWrapped=true)]
    public partial class createemployeeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public createemployeeResponse() {
        }
        
        public createemployeeResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="customerhasaddress", WrapperNamespace="", IsWrapped=true)]
    public partial class customerhasaddressRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int CustomerID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int AddressID;
        
        public customerhasaddressRequest() {
        }
        
        public customerhasaddressRequest(int CustomerID, int AddressID) {
            this.CustomerID = CustomerID;
            this.AddressID = AddressID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="customerhasaddressResponse", WrapperNamespace="", IsWrapped=true)]
    public partial class customerhasaddressResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public bool @return;
        
        public customerhasaddressResponse() {
        }
        
        public customerhasaddressResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="employeehasaddress", WrapperNamespace="", IsWrapped=true)]
    public partial class employeehasaddressRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int EmployeeID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int AddressID;
        
        public employeehasaddressRequest() {
        }
        
        public employeehasaddressRequest(int EmployeeID, int AddressID) {
            this.EmployeeID = EmployeeID;
            this.AddressID = AddressID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="employeehasaddressResponse", WrapperNamespace="", IsWrapped=true)]
    public partial class employeehasaddressResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public bool @return;
        
        public employeehasaddressResponse() {
        }
        
        public employeehasaddressResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createaddress", WrapperNamespace="", IsWrapped=true)]
    public partial class createaddressRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Ort;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int PLZ;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string Strasse;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string Hausnummer;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public int Postfach;
        
        public createaddressRequest() {
        }
        
        public createaddressRequest(string Ort, int PLZ, string Strasse, string Hausnummer, int Postfach) {
            this.Ort = Ort;
            this.PLZ = PLZ;
            this.Strasse = Strasse;
            this.Hausnummer = Hausnummer;
            this.Postfach = Postfach;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createaddressResponse", WrapperNamespace="", IsWrapped=true)]
    public partial class createaddressResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public createaddressResponse() {
        }
        
        public createaddressResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="startWork", WrapperNamespace="", IsWrapped=true)]
    public partial class startWorkRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string project;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string activity;
        
        public startWorkRequest() {
        }
        
        public startWorkRequest(string project, string activity) {
            this.project = project;
            this.activity = activity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="startWorkResponse", WrapperNamespace="", IsWrapped=true)]
    public partial class startWorkResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string @return;
        
        public startWorkResponse() {
        }
        
        public startWorkResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="stopWork", WrapperNamespace="", IsWrapped=true)]
    public partial class stopWorkRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string id;
        
        public stopWorkRequest() {
        }
        
        public stopWorkRequest(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="stopWorkResponse", WrapperNamespace="", IsWrapped=true)]
    public partial class stopWorkResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string @return;
        
        public stopWorkResponse() {
        }
        
        public stopWorkResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pauseWork", WrapperNamespace="", IsWrapped=true)]
    public partial class pauseWorkRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string id;
        
        public pauseWorkRequest() {
        }
        
        public pauseWorkRequest(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pauseWorkResponse", WrapperNamespace="", IsWrapped=true)]
    public partial class pauseWorkResponse {
        
        public pauseWorkResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="stopPauseWork", WrapperNamespace="", IsWrapped=true)]
    public partial class stopPauseWorkRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string id;
        
        public stopPauseWorkRequest() {
        }
        
        public stopPauseWorkRequest(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="stopPauseWorkResponse", WrapperNamespace="", IsWrapped=true)]
    public partial class stopPauseWorkResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string @return;
        
        public stopPauseWorkResponse() {
        }
        
        public stopPauseWorkResponse(string @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:dajana")]
    public partial class TableDataWorkingTimes : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idArbeitszeitField;
        
        private System.DateTime datumField;
        
        private System.DateTime anfangField;
        
        private System.DateTime endeField;
        
        private string projektField;
        
        private string aktivitaetField;
        
        private int dauerArbeitszeitField;
        
        private int ueberstundenField;
        
        private System.DateTime pauseAnfangField;
        
        private System.DateTime pauseEndeField;
        
        private int dauerPauseField;
        
        private int gesamtDauerArbeitszeitField;
        
        private int statusField;
        
        /// <remarks/>
        public int idArbeitszeit {
            get {
                return this.idArbeitszeitField;
            }
            set {
                this.idArbeitszeitField = value;
                this.RaisePropertyChanged("idArbeitszeit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="date")]
        public System.DateTime Datum {
            get {
                return this.datumField;
            }
            set {
                this.datumField = value;
                this.RaisePropertyChanged("Datum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="time")]
        public System.DateTime Anfang {
            get {
                return this.anfangField;
            }
            set {
                this.anfangField = value;
                this.RaisePropertyChanged("Anfang");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="time")]
        public System.DateTime Ende {
            get {
                return this.endeField;
            }
            set {
                this.endeField = value;
                this.RaisePropertyChanged("Ende");
            }
        }
        
        /// <remarks/>
        public string Projekt {
            get {
                return this.projektField;
            }
            set {
                this.projektField = value;
                this.RaisePropertyChanged("Projekt");
            }
        }
        
        /// <remarks/>
        public string Aktivitaet {
            get {
                return this.aktivitaetField;
            }
            set {
                this.aktivitaetField = value;
                this.RaisePropertyChanged("Aktivitaet");
            }
        }
        
        /// <remarks/>
        public int DauerArbeitszeit {
            get {
                return this.dauerArbeitszeitField;
            }
            set {
                this.dauerArbeitszeitField = value;
                this.RaisePropertyChanged("DauerArbeitszeit");
            }
        }
        
        /// <remarks/>
        public int Ueberstunden {
            get {
                return this.ueberstundenField;
            }
            set {
                this.ueberstundenField = value;
                this.RaisePropertyChanged("Ueberstunden");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="time")]
        public System.DateTime PauseAnfang {
            get {
                return this.pauseAnfangField;
            }
            set {
                this.pauseAnfangField = value;
                this.RaisePropertyChanged("PauseAnfang");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="time")]
        public System.DateTime PauseEnde {
            get {
                return this.pauseEndeField;
            }
            set {
                this.pauseEndeField = value;
                this.RaisePropertyChanged("PauseEnde");
            }
        }
        
        /// <remarks/>
        public int DauerPause {
            get {
                return this.dauerPauseField;
            }
            set {
                this.dauerPauseField = value;
                this.RaisePropertyChanged("DauerPause");
            }
        }
        
        /// <remarks/>
        public int GesamtDauerArbeitszeit {
            get {
                return this.gesamtDauerArbeitszeitField;
            }
            set {
                this.gesamtDauerArbeitszeitField = value;
                this.RaisePropertyChanged("GesamtDauerArbeitszeit");
            }
        }
        
        /// <remarks/>
        public int Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:dajana")]
    public partial class TableDataActivities : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idAktivitaetenField;
        
        private string aktivitaetennameField;
        
        private string aktivitaetenbeschreibungField;
        
        private int statusField;
        
        /// <remarks/>
        public int idAktivitaeten {
            get {
                return this.idAktivitaetenField;
            }
            set {
                this.idAktivitaetenField = value;
                this.RaisePropertyChanged("idAktivitaeten");
            }
        }
        
        /// <remarks/>
        public string Aktivitaetenname {
            get {
                return this.aktivitaetennameField;
            }
            set {
                this.aktivitaetennameField = value;
                this.RaisePropertyChanged("Aktivitaetenname");
            }
        }
        
        /// <remarks/>
        public string Aktivitaetenbeschreibung {
            get {
                return this.aktivitaetenbeschreibungField;
            }
            set {
                this.aktivitaetenbeschreibungField = value;
                this.RaisePropertyChanged("Aktivitaetenbeschreibung");
            }
        }
        
        /// <remarks/>
        public int Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:dajana")]
    public partial class TableDataProjects : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idProjektField;
        
        private string projektnameField;
        
        private string projektbeschreibungField;
        
        private int customer_KundenNrField;
        
        private int statusField;
        
        /// <remarks/>
        public int idProjekt {
            get {
                return this.idProjektField;
            }
            set {
                this.idProjektField = value;
                this.RaisePropertyChanged("idProjekt");
            }
        }
        
        /// <remarks/>
        public string Projektname {
            get {
                return this.projektnameField;
            }
            set {
                this.projektnameField = value;
                this.RaisePropertyChanged("Projektname");
            }
        }
        
        /// <remarks/>
        public string Projektbeschreibung {
            get {
                return this.projektbeschreibungField;
            }
            set {
                this.projektbeschreibungField = value;
                this.RaisePropertyChanged("Projektbeschreibung");
            }
        }
        
        /// <remarks/>
        public int customer_KundenNr {
            get {
                return this.customer_KundenNrField;
            }
            set {
                this.customer_KundenNrField = value;
                this.RaisePropertyChanged("customer_KundenNr");
            }
        }
        
        /// <remarks/>
        public int Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:dajana")]
    public partial class TableDataEmployees : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int persNrField;
        
        private string nachnameField;
        
        private string vornameField;
        
        private System.DateTime gebTagField;
        
        private string eMailField;
        
        private string telNrMobilField;
        
        private string telNrFestnetzField;
        
        private string abteilungField;
        
        private System.DateTime regelarbeitszeitField;
        
        private int statusField;
        
        /// <remarks/>
        public int PersNr {
            get {
                return this.persNrField;
            }
            set {
                this.persNrField = value;
                this.RaisePropertyChanged("PersNr");
            }
        }
        
        /// <remarks/>
        public string Nachname {
            get {
                return this.nachnameField;
            }
            set {
                this.nachnameField = value;
                this.RaisePropertyChanged("Nachname");
            }
        }
        
        /// <remarks/>
        public string Vorname {
            get {
                return this.vornameField;
            }
            set {
                this.vornameField = value;
                this.RaisePropertyChanged("Vorname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="date")]
        public System.DateTime GebTag {
            get {
                return this.gebTagField;
            }
            set {
                this.gebTagField = value;
                this.RaisePropertyChanged("GebTag");
            }
        }
        
        /// <remarks/>
        public string EMail {
            get {
                return this.eMailField;
            }
            set {
                this.eMailField = value;
                this.RaisePropertyChanged("EMail");
            }
        }
        
        /// <remarks/>
        public string TelNrMobil {
            get {
                return this.telNrMobilField;
            }
            set {
                this.telNrMobilField = value;
                this.RaisePropertyChanged("TelNrMobil");
            }
        }
        
        /// <remarks/>
        public string TelNrFestnetz {
            get {
                return this.telNrFestnetzField;
            }
            set {
                this.telNrFestnetzField = value;
                this.RaisePropertyChanged("TelNrFestnetz");
            }
        }
        
        /// <remarks/>
        public string Abteilung {
            get {
                return this.abteilungField;
            }
            set {
                this.abteilungField = value;
                this.RaisePropertyChanged("Abteilung");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="time")]
        public System.DateTime Regelarbeitszeit {
            get {
                return this.regelarbeitszeitField;
            }
            set {
                this.regelarbeitszeitField = value;
                this.RaisePropertyChanged("Regelarbeitszeit");
            }
        }
        
        /// <remarks/>
        public int Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:dajana")]
    public partial class TableDataCustomers : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int kundenNrField;
        
        private string nachnameField;
        
        private string vornameField;
        
        private string firmennameField;
        
        private string telNrMobilField;
        
        private string telNrFestnetzField;
        
        private string eMailField;
        
        private int statusField;
        
        /// <remarks/>
        public int KundenNr {
            get {
                return this.kundenNrField;
            }
            set {
                this.kundenNrField = value;
                this.RaisePropertyChanged("KundenNr");
            }
        }
        
        /// <remarks/>
        public string Nachname {
            get {
                return this.nachnameField;
            }
            set {
                this.nachnameField = value;
                this.RaisePropertyChanged("Nachname");
            }
        }
        
        /// <remarks/>
        public string Vorname {
            get {
                return this.vornameField;
            }
            set {
                this.vornameField = value;
                this.RaisePropertyChanged("Vorname");
            }
        }
        
        /// <remarks/>
        public string Firmenname {
            get {
                return this.firmennameField;
            }
            set {
                this.firmennameField = value;
                this.RaisePropertyChanged("Firmenname");
            }
        }
        
        /// <remarks/>
        public string TelNrMobil {
            get {
                return this.telNrMobilField;
            }
            set {
                this.telNrMobilField = value;
                this.RaisePropertyChanged("TelNrMobil");
            }
        }
        
        /// <remarks/>
        public string TelNrFestnetz {
            get {
                return this.telNrFestnetzField;
            }
            set {
                this.telNrFestnetzField = value;
                this.RaisePropertyChanged("TelNrFestnetz");
            }
        }
        
        /// <remarks/>
        public string EMail {
            get {
                return this.eMailField;
            }
            set {
                this.eMailField = value;
                this.RaisePropertyChanged("EMail");
            }
        }
        
        /// <remarks/>
        public int Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface zeiterfassungPortTypeChannel : WpfApplication3.ServiceReference1.zeiterfassungPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class zeiterfassungPortTypeClient : System.ServiceModel.ClientBase<WpfApplication3.ServiceReference1.zeiterfassungPortType>, WpfApplication3.ServiceReference1.zeiterfassungPortType {
        
        public zeiterfassungPortTypeClient() {
        }
        
        public zeiterfassungPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public zeiterfassungPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public zeiterfassungPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public zeiterfassungPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfApplication3.ServiceReference1.checkLoginResponse WpfApplication3.ServiceReference1.zeiterfassungPortType.checkLogin(WpfApplication3.ServiceReference1.checkLoginRequest request) {
            return base.Channel.checkLogin(request);
        }
        
        public bool checkLogin(string persnr, int pin) {
            WpfApplication3.ServiceReference1.checkLoginRequest inValue = new WpfApplication3.ServiceReference1.checkLoginRequest();
            inValue.persnr = persnr;
            inValue.pin = pin;
            WpfApplication3.ServiceReference1.checkLoginResponse retVal = ((WpfApplication3.ServiceReference1.zeiterfassungPortType)(this)).checkLogin(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.checkLoginResponse> WpfApplication3.ServiceReference1.zeiterfassungPortType.checkLoginAsync(WpfApplication3.ServiceReference1.checkLoginRequest request) {
            return base.Channel.checkLoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.checkLoginResponse> checkLoginAsync(string persnr, int pin) {
            WpfApplication3.ServiceReference1.checkLoginRequest inValue = new WpfApplication3.ServiceReference1.checkLoginRequest();
            inValue.persnr = persnr;
            inValue.pin = pin;
            return ((WpfApplication3.ServiceReference1.zeiterfassungPortType)(this)).checkLoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfApplication3.ServiceReference1.createprojectResponse WpfApplication3.ServiceReference1.zeiterfassungPortType.createproject(WpfApplication3.ServiceReference1.createprojectRequest request) {
            return base.Channel.createproject(request);
        }
        
        public int createproject(int idprojekt, string projektname, string projektbeschreibung, int status, int kundennr) {
            WpfApplication3.ServiceReference1.createprojectRequest inValue = new WpfApplication3.ServiceReference1.createprojectRequest();
            inValue.idprojekt = idprojekt;
            inValue.projektname = projektname;
            inValue.projektbeschreibung = projektbeschreibung;
            inValue.status = status;
            inValue.kundennr = kundennr;
            WpfApplication3.ServiceReference1.createprojectResponse retVal = ((WpfApplication3.ServiceReference1.zeiterfassungPortType)(this)).createproject(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.createprojectResponse> WpfApplication3.ServiceReference1.zeiterfassungPortType.createprojectAsync(WpfApplication3.ServiceReference1.createprojectRequest request) {
            return base.Channel.createprojectAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.createprojectResponse> createprojectAsync(int idprojekt, string projektname, string projektbeschreibung, int status, int kundennr) {
            WpfApplication3.ServiceReference1.createprojectRequest inValue = new WpfApplication3.ServiceReference1.createprojectRequest();
            inValue.idprojekt = idprojekt;
            inValue.projektname = projektname;
            inValue.projektbeschreibung = projektbeschreibung;
            inValue.status = status;
            inValue.kundennr = kundennr;
            return ((WpfApplication3.ServiceReference1.zeiterfassungPortType)(this)).createprojectAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfApplication3.ServiceReference1.selectedcustomerResponse WpfApplication3.ServiceReference1.zeiterfassungPortType.selectedcustomer(WpfApplication3.ServiceReference1.selectedcustomerRequest request) {
            return base.Channel.selectedcustomer(request);
        }
        
        public int selectedcustomer(string Firmenname) {
            WpfApplication3.ServiceReference1.selectedcustomerRequest inValue = new WpfApplication3.ServiceReference1.selectedcustomerRequest();
            inValue.Firmenname = Firmenname;
            WpfApplication3.ServiceReference1.selectedcustomerResponse retVal = ((WpfApplication3.ServiceReference1.zeiterfassungPortType)(this)).selectedcustomer(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.selectedcustomerResponse> WpfApplication3.ServiceReference1.zeiterfassungPortType.selectedcustomerAsync(WpfApplication3.ServiceReference1.selectedcustomerRequest request) {
            return base.Channel.selectedcustomerAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.selectedcustomerResponse> selectedcustomerAsync(string Firmenname) {
            WpfApplication3.ServiceReference1.selectedcustomerRequest inValue = new WpfApplication3.ServiceReference1.selectedcustomerRequest();
            inValue.Firmenname = Firmenname;
            return ((WpfApplication3.ServiceReference1.zeiterfassungPortType)(this)).selectedcustomerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfApplication3.ServiceReference1.createcustomerResponse WpfApplication3.ServiceReference1.zeiterfassungPortType.createcustomer(WpfApplication3.ServiceReference1.createcustomerRequest request) {
            return base.Channel.createcustomer(request);
        }
        
        public int createcustomer(int KundenNr, string Nachname, string Vorname, string Firmenname, string TelNrMobil, string TelNrFestnetz, string EMail, int Status) {
            WpfApplication3.ServiceReference1.createcustomerRequest inValue = new WpfApplication3.ServiceReference1.createcustomerRequest();
            inValue.KundenNr = KundenNr;
            inValue.Nachname = Nachname;
            inValue.Vorname = Vorname;
            inValue.Firmenname = Firmenname;
            inValue.TelNrMobil = TelNrMobil;
            inValue.TelNrFestnetz = TelNrFestnetz;
            inValue.EMail = EMail;
            inValue.Status = Status;
            WpfApplication3.ServiceReference1.createcustomerResponse retVal = ((WpfApplication3.ServiceReference1.zeiterfassungPortType)(this)).createcustomer(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.createcustomerResponse> WpfApplication3.ServiceReference1.zeiterfassungPortType.createcustomerAsync(WpfApplication3.ServiceReference1.createcustomerRequest request) {
            return base.Channel.createcustomerAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.createcustomerResponse> createcustomerAsync(int KundenNr, string Nachname, string Vorname, string Firmenname, string TelNrMobil, string TelNrFestnetz, string EMail, int Status) {
            WpfApplication3.ServiceReference1.createcustomerRequest inValue = new WpfApplication3.ServiceReference1.createcustomerRequest();
            inValue.KundenNr = KundenNr;
            inValue.Nachname = Nachname;
            inValue.Vorname = Vorname;
            inValue.Firmenname = Firmenname;
            inValue.TelNrMobil = TelNrMobil;
            inValue.TelNrFestnetz = TelNrFestnetz;
            inValue.EMail = EMail;
            inValue.Status = Status;
            return ((WpfApplication3.ServiceReference1.zeiterfassungPortType)(this)).createcustomerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfApplication3.ServiceReference1.createemployeeResponse WpfApplication3.ServiceReference1.zeiterfassungPortType.createemployee(WpfApplication3.ServiceReference1.createemployeeRequest request) {
            return base.Channel.createemployee(request);
        }
        
        public int createemployee(int MitarbeiterNr, string Nachname, string Vorname, string GebTag, string Abteilung, string TelNrMobil, string TelNrFestnetz, string EMail, int Berechtigungsstufe, int PIN, bool Status) {
            WpfApplication3.ServiceReference1.createemployeeRequest inValue = new WpfApplication3.ServiceReference1.createemployeeRequest();
            inValue.MitarbeiterNr = MitarbeiterNr;
            inValue.Nachname = Nachname;
            inValue.Vorname = Vorname;
            inValue.GebTag = GebTag;
            inValue.Abteilung = Abteilung;
            inValue.TelNrMobil = TelNrMobil;
            inValue.TelNrFestnetz = TelNrFestnetz;
            inValue.EMail = EMail;
            inValue.Berechtigungsstufe = Berechtigungsstufe;
            inValue.PIN = PIN;
            inValue.Status = Status;
            WpfApplication3.ServiceReference1.createemployeeResponse retVal = ((WpfApplication3.ServiceReference1.zeiterfassungPortType)(this)).createemployee(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.createemployeeResponse> WpfApplication3.ServiceReference1.zeiterfassungPortType.createemployeeAsync(WpfApplication3.ServiceReference1.createemployeeRequest request) {
            return base.Channel.createemployeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.createemployeeResponse> createemployeeAsync(int MitarbeiterNr, string Nachname, string Vorname, string GebTag, string Abteilung, string TelNrMobil, string TelNrFestnetz, string EMail, int Berechtigungsstufe, int PIN, bool Status) {
            WpfApplication3.ServiceReference1.createemployeeRequest inValue = new WpfApplication3.ServiceReference1.createemployeeRequest();
            inValue.MitarbeiterNr = MitarbeiterNr;
            inValue.Nachname = Nachname;
            inValue.Vorname = Vorname;
            inValue.GebTag = GebTag;
            inValue.Abteilung = Abteilung;
            inValue.TelNrMobil = TelNrMobil;
            inValue.TelNrFestnetz = TelNrFestnetz;
            inValue.EMail = EMail;
            inValue.Berechtigungsstufe = Berechtigungsstufe;
            inValue.PIN = PIN;
            inValue.Status = Status;
            return ((WpfApplication3.ServiceReference1.zeiterfassungPortType)(this)).createemployeeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfApplication3.ServiceReference1.customerhasaddressResponse WpfApplication3.ServiceReference1.zeiterfassungPortType.customerhasaddress(WpfApplication3.ServiceReference1.customerhasaddressRequest request) {
            return base.Channel.customerhasaddress(request);
        }
        
        public bool customerhasaddress(int CustomerID, int AddressID) {
            WpfApplication3.ServiceReference1.customerhasaddressRequest inValue = new WpfApplication3.ServiceReference1.customerhasaddressRequest();
            inValue.CustomerID = CustomerID;
            inValue.AddressID = AddressID;
            WpfApplication3.ServiceReference1.customerhasaddressResponse retVal = ((WpfApplication3.ServiceReference1.zeiterfassungPortType)(this)).customerhasaddress(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.customerhasaddressResponse> WpfApplication3.ServiceReference1.zeiterfassungPortType.customerhasaddressAsync(WpfApplication3.ServiceReference1.customerhasaddressRequest request) {
            return base.Channel.customerhasaddressAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.customerhasaddressResponse> customerhasaddressAsync(int CustomerID, int AddressID) {
            WpfApplication3.ServiceReference1.customerhasaddressRequest inValue = new WpfApplication3.ServiceReference1.customerhasaddressRequest();
            inValue.CustomerID = CustomerID;
            inValue.AddressID = AddressID;
            return ((WpfApplication3.ServiceReference1.zeiterfassungPortType)(this)).customerhasaddressAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfApplication3.ServiceReference1.employeehasaddressResponse WpfApplication3.ServiceReference1.zeiterfassungPortType.employeehasaddress(WpfApplication3.ServiceReference1.employeehasaddressRequest request) {
            return base.Channel.employeehasaddress(request);
        }
        
        public bool employeehasaddress(int EmployeeID, int AddressID) {
            WpfApplication3.ServiceReference1.employeehasaddressRequest inValue = new WpfApplication3.ServiceReference1.employeehasaddressRequest();
            inValue.EmployeeID = EmployeeID;
            inValue.AddressID = AddressID;
            WpfApplication3.ServiceReference1.employeehasaddressResponse retVal = ((WpfApplication3.ServiceReference1.zeiterfassungPortType)(this)).employeehasaddress(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.employeehasaddressResponse> WpfApplication3.ServiceReference1.zeiterfassungPortType.employeehasaddressAsync(WpfApplication3.ServiceReference1.employeehasaddressRequest request) {
            return base.Channel.employeehasaddressAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.employeehasaddressResponse> employeehasaddressAsync(int EmployeeID, int AddressID) {
            WpfApplication3.ServiceReference1.employeehasaddressRequest inValue = new WpfApplication3.ServiceReference1.employeehasaddressRequest();
            inValue.EmployeeID = EmployeeID;
            inValue.AddressID = AddressID;
            return ((WpfApplication3.ServiceReference1.zeiterfassungPortType)(this)).employeehasaddressAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfApplication3.ServiceReference1.createaddressResponse WpfApplication3.ServiceReference1.zeiterfassungPortType.createaddress(WpfApplication3.ServiceReference1.createaddressRequest request) {
            return base.Channel.createaddress(request);
        }
        
        public int createaddress(string Ort, int PLZ, string Strasse, string Hausnummer, int Postfach) {
            WpfApplication3.ServiceReference1.createaddressRequest inValue = new WpfApplication3.ServiceReference1.createaddressRequest();
            inValue.Ort = Ort;
            inValue.PLZ = PLZ;
            inValue.Strasse = Strasse;
            inValue.Hausnummer = Hausnummer;
            inValue.Postfach = Postfach;
            WpfApplication3.ServiceReference1.createaddressResponse retVal = ((WpfApplication3.ServiceReference1.zeiterfassungPortType)(this)).createaddress(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.createaddressResponse> WpfApplication3.ServiceReference1.zeiterfassungPortType.createaddressAsync(WpfApplication3.ServiceReference1.createaddressRequest request) {
            return base.Channel.createaddressAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.createaddressResponse> createaddressAsync(string Ort, int PLZ, string Strasse, string Hausnummer, int Postfach) {
            WpfApplication3.ServiceReference1.createaddressRequest inValue = new WpfApplication3.ServiceReference1.createaddressRequest();
            inValue.Ort = Ort;
            inValue.PLZ = PLZ;
            inValue.Strasse = Strasse;
            inValue.Hausnummer = Hausnummer;
            inValue.Postfach = Postfach;
            return ((WpfApplication3.ServiceReference1.zeiterfassungPortType)(this)).createaddressAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfApplication3.ServiceReference1.startWorkResponse WpfApplication3.ServiceReference1.zeiterfassungPortType.startWork(WpfApplication3.ServiceReference1.startWorkRequest request) {
            return base.Channel.startWork(request);
        }
        
        public string startWork(string project, string activity) {
            WpfApplication3.ServiceReference1.startWorkRequest inValue = new WpfApplication3.ServiceReference1.startWorkRequest();
            inValue.project = project;
            inValue.activity = activity;
            WpfApplication3.ServiceReference1.startWorkResponse retVal = ((WpfApplication3.ServiceReference1.zeiterfassungPortType)(this)).startWork(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.startWorkResponse> WpfApplication3.ServiceReference1.zeiterfassungPortType.startWorkAsync(WpfApplication3.ServiceReference1.startWorkRequest request) {
            return base.Channel.startWorkAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.startWorkResponse> startWorkAsync(string project, string activity) {
            WpfApplication3.ServiceReference1.startWorkRequest inValue = new WpfApplication3.ServiceReference1.startWorkRequest();
            inValue.project = project;
            inValue.activity = activity;
            return ((WpfApplication3.ServiceReference1.zeiterfassungPortType)(this)).startWorkAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfApplication3.ServiceReference1.stopWorkResponse WpfApplication3.ServiceReference1.zeiterfassungPortType.stopWork(WpfApplication3.ServiceReference1.stopWorkRequest request) {
            return base.Channel.stopWork(request);
        }
        
        public string stopWork(string id) {
            WpfApplication3.ServiceReference1.stopWorkRequest inValue = new WpfApplication3.ServiceReference1.stopWorkRequest();
            inValue.id = id;
            WpfApplication3.ServiceReference1.stopWorkResponse retVal = ((WpfApplication3.ServiceReference1.zeiterfassungPortType)(this)).stopWork(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.stopWorkResponse> WpfApplication3.ServiceReference1.zeiterfassungPortType.stopWorkAsync(WpfApplication3.ServiceReference1.stopWorkRequest request) {
            return base.Channel.stopWorkAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.stopWorkResponse> stopWorkAsync(string id) {
            WpfApplication3.ServiceReference1.stopWorkRequest inValue = new WpfApplication3.ServiceReference1.stopWorkRequest();
            inValue.id = id;
            return ((WpfApplication3.ServiceReference1.zeiterfassungPortType)(this)).stopWorkAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfApplication3.ServiceReference1.pauseWorkResponse WpfApplication3.ServiceReference1.zeiterfassungPortType.pauseWork(WpfApplication3.ServiceReference1.pauseWorkRequest request) {
            return base.Channel.pauseWork(request);
        }
        
        public void pauseWork(string id) {
            WpfApplication3.ServiceReference1.pauseWorkRequest inValue = new WpfApplication3.ServiceReference1.pauseWorkRequest();
            inValue.id = id;
            WpfApplication3.ServiceReference1.pauseWorkResponse retVal = ((WpfApplication3.ServiceReference1.zeiterfassungPortType)(this)).pauseWork(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.pauseWorkResponse> WpfApplication3.ServiceReference1.zeiterfassungPortType.pauseWorkAsync(WpfApplication3.ServiceReference1.pauseWorkRequest request) {
            return base.Channel.pauseWorkAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.pauseWorkResponse> pauseWorkAsync(string id) {
            WpfApplication3.ServiceReference1.pauseWorkRequest inValue = new WpfApplication3.ServiceReference1.pauseWorkRequest();
            inValue.id = id;
            return ((WpfApplication3.ServiceReference1.zeiterfassungPortType)(this)).pauseWorkAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfApplication3.ServiceReference1.stopPauseWorkResponse WpfApplication3.ServiceReference1.zeiterfassungPortType.stopPauseWork(WpfApplication3.ServiceReference1.stopPauseWorkRequest request) {
            return base.Channel.stopPauseWork(request);
        }
        
        public string stopPauseWork(string id) {
            WpfApplication3.ServiceReference1.stopPauseWorkRequest inValue = new WpfApplication3.ServiceReference1.stopPauseWorkRequest();
            inValue.id = id;
            WpfApplication3.ServiceReference1.stopPauseWorkResponse retVal = ((WpfApplication3.ServiceReference1.zeiterfassungPortType)(this)).stopPauseWork(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.stopPauseWorkResponse> WpfApplication3.ServiceReference1.zeiterfassungPortType.stopPauseWorkAsync(WpfApplication3.ServiceReference1.stopPauseWorkRequest request) {
            return base.Channel.stopPauseWorkAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.stopPauseWorkResponse> stopPauseWorkAsync(string id) {
            WpfApplication3.ServiceReference1.stopPauseWorkRequest inValue = new WpfApplication3.ServiceReference1.stopPauseWorkRequest();
            inValue.id = id;
            return ((WpfApplication3.ServiceReference1.zeiterfassungPortType)(this)).stopPauseWorkAsync(inValue);
        }
        
        public string[] loadprojects() {
            return base.Channel.loadprojects();
        }
        
        public System.Threading.Tasks.Task<string[]> loadprojectsAsync() {
            return base.Channel.loadprojectsAsync();
        }
        
        public string[] loadcustomers() {
            return base.Channel.loadcustomers();
        }
        
        public System.Threading.Tasks.Task<string[]> loadcustomersAsync() {
            return base.Channel.loadcustomersAsync();
        }
        
        public string[] loadactivities() {
            return base.Channel.loadactivities();
        }
        
        public System.Threading.Tasks.Task<string[]> loadactivitiesAsync() {
            return base.Channel.loadactivitiesAsync();
        }
        
        public string[] loadauthorisations() {
            return base.Channel.loadauthorisations();
        }
        
        public System.Threading.Tasks.Task<string[]> loadauthorisationsAsync() {
            return base.Channel.loadauthorisationsAsync();
        }
        
        public WpfApplication3.ServiceReference1.TableDataWorkingTimes[] loadtableworkingtimes() {
            return base.Channel.loadtableworkingtimes();
        }
        
        public System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.TableDataWorkingTimes[]> loadtableworkingtimesAsync() {
            return base.Channel.loadtableworkingtimesAsync();
        }
        
        public WpfApplication3.ServiceReference1.TableDataCustomers[] loadtablecustomers() {
            return base.Channel.loadtablecustomers();
        }
        
        public System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.TableDataCustomers[]> loadtablecustomersAsync() {
            return base.Channel.loadtablecustomersAsync();
        }
        
        public WpfApplication3.ServiceReference1.TableDataEmployees[] loadtableemployees() {
            return base.Channel.loadtableemployees();
        }
        
        public System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.TableDataEmployees[]> loadtableemployeesAsync() {
            return base.Channel.loadtableemployeesAsync();
        }
        
        public WpfApplication3.ServiceReference1.TableDataProjects[] loadtableprojects() {
            return base.Channel.loadtableprojects();
        }
        
        public System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.TableDataProjects[]> loadtableprojectsAsync() {
            return base.Channel.loadtableprojectsAsync();
        }
        
        public WpfApplication3.ServiceReference1.TableDataActivities[] loadtableactivities() {
            return base.Channel.loadtableactivities();
        }
        
        public System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.TableDataActivities[]> loadtableactivitiesAsync() {
            return base.Channel.loadtableactivitiesAsync();
        }
    }
}
