//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication3.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:dajana", ConfigurationName="ServiceReference1.zeiterfassungPortType")]
    public interface zeiterfassungPortType {
        
        // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Wrappernamespace () von Nachricht "checkAuthentificationRequest" nicht mit dem Standardwert (urn:dajana) übereinstimmt.
        [System.ServiceModel.OperationContractAttribute(Action="http://193.196.143.148/soap/index.php/checkAuthentification", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WpfApplication3.ServiceReference1.checkAuthentificationResponse checkAuthentification(WpfApplication3.ServiceReference1.checkAuthentificationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://193.196.143.148/soap/index.php/checkAuthentification", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.checkAuthentificationResponse> checkAuthentificationAsync(WpfApplication3.ServiceReference1.checkAuthentificationRequest request);
        
        // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Wrappernamespace () von Nachricht "createprojectRequest" nicht mit dem Standardwert (urn:dajana) übereinstimmt.
        [System.ServiceModel.OperationContractAttribute(Action="http://193.196.143.148/soap/index.php/createproject", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WpfApplication3.ServiceReference1.createprojectResponse createproject(WpfApplication3.ServiceReference1.createprojectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://193.196.143.148/soap/index.php/createproject", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.createprojectResponse> createprojectAsync(WpfApplication3.ServiceReference1.createprojectRequest request);
        
        // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Wrappernamespace () von Nachricht "selectedcustomerRequest" nicht mit dem Standardwert (urn:dajana) übereinstimmt.
        [System.ServiceModel.OperationContractAttribute(Action="http://193.196.143.148/soap/index.php/selectedcustomer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WpfApplication3.ServiceReference1.selectedcustomerResponse selectedcustomer(WpfApplication3.ServiceReference1.selectedcustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://193.196.143.148/soap/index.php/selectedcustomer", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.selectedcustomerResponse> selectedcustomerAsync(WpfApplication3.ServiceReference1.selectedcustomerRequest request);
        
        // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Wrappernamespace () von Nachricht "createcustomerRequest" nicht mit dem Standardwert (urn:dajana) übereinstimmt.
        [System.ServiceModel.OperationContractAttribute(Action="http://193.196.143.148/soap/index.php/createcustomer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WpfApplication3.ServiceReference1.createcustomerResponse createcustomer(WpfApplication3.ServiceReference1.createcustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://193.196.143.148/soap/index.php/createcustomer", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.createcustomerResponse> createcustomerAsync(WpfApplication3.ServiceReference1.createcustomerRequest request);
        
        // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Wrappernamespace () von Nachricht "createemployeeRequest" nicht mit dem Standardwert (urn:dajana) übereinstimmt.
        [System.ServiceModel.OperationContractAttribute(Action="http://193.196.143.148/soap/index.php/createemployee", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WpfApplication3.ServiceReference1.createemployeeResponse createemployee(WpfApplication3.ServiceReference1.createemployeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://193.196.143.148/soap/index.php/createemployee", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.createemployeeResponse> createemployeeAsync(WpfApplication3.ServiceReference1.createemployeeRequest request);
        
        // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Wrappernamespace () von Nachricht "customerhasaddressRequest" nicht mit dem Standardwert (urn:dajana) übereinstimmt.
        [System.ServiceModel.OperationContractAttribute(Action="http://193.196.143.148/soap/index.php/customerhasaddress", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WpfApplication3.ServiceReference1.customerhasaddressResponse customerhasaddress(WpfApplication3.ServiceReference1.customerhasaddressRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://193.196.143.148/soap/index.php/customerhasaddress", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.customerhasaddressResponse> customerhasaddressAsync(WpfApplication3.ServiceReference1.customerhasaddressRequest request);
        
        // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Wrappernamespace () von Nachricht "employeehasaddressRequest" nicht mit dem Standardwert (urn:dajana) übereinstimmt.
        [System.ServiceModel.OperationContractAttribute(Action="http://193.196.143.148/soap/index.php/employeehasaddress", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WpfApplication3.ServiceReference1.employeehasaddressResponse employeehasaddress(WpfApplication3.ServiceReference1.employeehasaddressRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://193.196.143.148/soap/index.php/employeehasaddress", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.employeehasaddressResponse> employeehasaddressAsync(WpfApplication3.ServiceReference1.employeehasaddressRequest request);
        
        // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Wrappernamespace () von Nachricht "createaddressRequest" nicht mit dem Standardwert (urn:dajana) übereinstimmt.
        [System.ServiceModel.OperationContractAttribute(Action="http://193.196.143.148/soap/index.php/createaddress", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WpfApplication3.ServiceReference1.createaddressResponse createaddress(WpfApplication3.ServiceReference1.createaddressRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://193.196.143.148/soap/index.php/createaddress", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.createaddressResponse> createaddressAsync(WpfApplication3.ServiceReference1.createaddressRequest request);
        
        // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Wrappernamespace () von Nachricht "startWorkRequest" nicht mit dem Standardwert (urn:dajana) übereinstimmt.
        [System.ServiceModel.OperationContractAttribute(Action="http://193.196.143.148/soap/index.php/startWork", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WpfApplication3.ServiceReference1.startWorkResponse startWork(WpfApplication3.ServiceReference1.startWorkRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://193.196.143.148/soap/index.php/startWork", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.startWorkResponse> startWorkAsync(WpfApplication3.ServiceReference1.startWorkRequest request);
        
        // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Wrappernamespace () von Nachricht "stopWorkRequest" nicht mit dem Standardwert (urn:dajana) übereinstimmt.
        [System.ServiceModel.OperationContractAttribute(Action="http://193.196.143.148/soap/index.php/stopWork", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WpfApplication3.ServiceReference1.stopWorkResponse stopWork(WpfApplication3.ServiceReference1.stopWorkRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://193.196.143.148/soap/index.php/stopWork", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.stopWorkResponse> stopWorkAsync(WpfApplication3.ServiceReference1.stopWorkRequest request);
        
        // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Wrappernamespace () von Nachricht "pauseWorkRequest" nicht mit dem Standardwert (urn:dajana) übereinstimmt.
        [System.ServiceModel.OperationContractAttribute(Action="http://193.196.143.148/soap/index.php/pauseWork", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WpfApplication3.ServiceReference1.pauseWorkResponse pauseWork(WpfApplication3.ServiceReference1.pauseWorkRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://193.196.143.148/soap/index.php/pauseWork", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.pauseWorkResponse> pauseWorkAsync(WpfApplication3.ServiceReference1.pauseWorkRequest request);
        
        // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Wrappernamespace () von Nachricht "stopPauseWorkRequest" nicht mit dem Standardwert (urn:dajana) übereinstimmt.
        [System.ServiceModel.OperationContractAttribute(Action="http://193.196.143.148/soap/index.php/stopPauseWork", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WpfApplication3.ServiceReference1.stopPauseWorkResponse stopPauseWork(WpfApplication3.ServiceReference1.stopPauseWorkRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://193.196.143.148/soap/index.php/stopPauseWork", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.stopPauseWorkResponse> stopPauseWorkAsync(WpfApplication3.ServiceReference1.stopPauseWorkRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="rpc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string[] loadprojects();
        
        [System.ServiceModel.OperationContractAttribute(Action="rpc", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string[]> loadprojectsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="rpc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string[] loadcustomers();
        
        [System.ServiceModel.OperationContractAttribute(Action="rpc", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string[]> loadcustomersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="rpc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string[] loadactivities();
        
        [System.ServiceModel.OperationContractAttribute(Action="rpc", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string[]> loadactivitiesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="rpc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string[] loadauthorisations();
        
        [System.ServiceModel.OperationContractAttribute(Action="rpc", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string[]> loadauthorisationsAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="checkAuthentification", WrapperNamespace="", IsWrapped=true)]
    public partial class checkAuthentificationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string persnr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int pin;
        
        public checkAuthentificationRequest() {
        }
        
        public checkAuthentificationRequest(string persnr, int pin) {
            this.persnr = persnr;
            this.pin = pin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="checkAuthentificationResponse", WrapperNamespace="", IsWrapped=true)]
    public partial class checkAuthentificationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public bool @return;
        
        public checkAuthentificationResponse() {
        }
        
        public checkAuthentificationResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createproject", WrapperNamespace="", IsWrapped=true)]
    public partial class createprojectRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int idprojekt;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string projektname;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string projektbeschreibung;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public int status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public int kundennr;
        
        public createprojectRequest() {
        }
        
        public createprojectRequest(int idprojekt, string projektname, string projektbeschreibung, int status, int kundennr) {
            this.idprojekt = idprojekt;
            this.projektname = projektname;
            this.projektbeschreibung = projektbeschreibung;
            this.status = status;
            this.kundennr = kundennr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createprojectResponse", WrapperNamespace="", IsWrapped=true)]
    public partial class createprojectResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public createprojectResponse() {
        }
        
        public createprojectResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="selectedcustomer", WrapperNamespace="", IsWrapped=true)]
    public partial class selectedcustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Firmenname;
        
        public selectedcustomerRequest() {
        }
        
        public selectedcustomerRequest(string Firmenname) {
            this.Firmenname = Firmenname;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="selectedcustomerResponse", WrapperNamespace="", IsWrapped=true)]
    public partial class selectedcustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public selectedcustomerResponse() {
        }
        
        public selectedcustomerResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createcustomer", WrapperNamespace="", IsWrapped=true)]
    public partial class createcustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int KundenNr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Nachname;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string Vorname;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string Firmenname;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string TelNrMobil;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string TelNrFestnetz;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string EMail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public int Status;
        
        public createcustomerRequest() {
        }
        
        public createcustomerRequest(int KundenNr, string Nachname, string Vorname, string Firmenname, string TelNrMobil, string TelNrFestnetz, string EMail, int Status) {
            this.KundenNr = KundenNr;
            this.Nachname = Nachname;
            this.Vorname = Vorname;
            this.Firmenname = Firmenname;
            this.TelNrMobil = TelNrMobil;
            this.TelNrFestnetz = TelNrFestnetz;
            this.EMail = EMail;
            this.Status = Status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createcustomerResponse", WrapperNamespace="", IsWrapped=true)]
    public partial class createcustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public createcustomerResponse() {
        }
        
        public createcustomerResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createemployee", WrapperNamespace="", IsWrapped=true)]
    public partial class createemployeeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int MitarbeiterNr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Nachname;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string Vorname;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string Abteilung;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        [System.Xml.Serialization.SoapElementAttribute(DataType="time")]
        public System.DateTime Regelsarbeitszeit;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        [System.Xml.Serialization.SoapElementAttribute(DataType="date")]
        public System.DateTime GebTag;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string TelNrMobil;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public string TelNrFestnetz;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
        public string EMail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=9)]
        public int Berechtigungsstufe;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=10)]
        public int PIN;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=11)]
        public int Status;
        
        public createemployeeRequest() {
        }
        
        public createemployeeRequest(int MitarbeiterNr, string Nachname, string Vorname, string Abteilung, System.DateTime Regelsarbeitszeit, System.DateTime GebTag, string TelNrMobil, string TelNrFestnetz, string EMail, int Berechtigungsstufe, int PIN, int Status) {
            this.MitarbeiterNr = MitarbeiterNr;
            this.Nachname = Nachname;
            this.Vorname = Vorname;
            this.Abteilung = Abteilung;
            this.Regelsarbeitszeit = Regelsarbeitszeit;
            this.GebTag = GebTag;
            this.TelNrMobil = TelNrMobil;
            this.TelNrFestnetz = TelNrFestnetz;
            this.EMail = EMail;
            this.Berechtigungsstufe = Berechtigungsstufe;
            this.PIN = PIN;
            this.Status = Status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createemployeeResponse", WrapperNamespace="", IsWrapped=true)]
    public partial class createemployeeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public createemployeeResponse() {
        }
        
        public createemployeeResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="customerhasaddress", WrapperNamespace="", IsWrapped=true)]
    public partial class customerhasaddressRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int CustomerID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int AddressID;
        
        public customerhasaddressRequest() {
        }
        
        public customerhasaddressRequest(int CustomerID, int AddressID) {
            this.CustomerID = CustomerID;
            this.AddressID = AddressID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="customerhasaddressResponse", WrapperNamespace="", IsWrapped=true)]
    public partial class customerhasaddressResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public bool @return;
        
        public customerhasaddressResponse() {
        }
        
        public customerhasaddressResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="employeehasaddress", WrapperNamespace="", IsWrapped=true)]
    public partial class employeehasaddressRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int EmployeeID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int AddressID;
        
        public employeehasaddressRequest() {
        }
        
        public employeehasaddressRequest(int EmployeeID, int AddressID) {
            this.EmployeeID = EmployeeID;
            this.AddressID = AddressID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="employeehasaddressResponse", WrapperNamespace="", IsWrapped=true)]
    public partial class employeehasaddressResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public bool @return;
        
        public employeehasaddressResponse() {
        }
        
        public employeehasaddressResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createaddress", WrapperNamespace="", IsWrapped=true)]
    public partial class createaddressRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Ort;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int PLZ;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string Strasse;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string Hausnummer;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public int Postfach;
        
        public createaddressRequest() {
        }
        
        public createaddressRequest(string Ort, int PLZ, string Strasse, string Hausnummer, int Postfach) {
            this.Ort = Ort;
            this.PLZ = PLZ;
            this.Strasse = Strasse;
            this.Hausnummer = Hausnummer;
            this.Postfach = Postfach;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createaddressResponse", WrapperNamespace="", IsWrapped=true)]
    public partial class createaddressResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public createaddressResponse() {
        }
        
        public createaddressResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="startWork", WrapperNamespace="", IsWrapped=true)]
    public partial class startWorkRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string project;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string activity;
        
        public startWorkRequest() {
        }
        
        public startWorkRequest(string project, string activity) {
            this.project = project;
            this.activity = activity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="startWorkResponse", WrapperNamespace="", IsWrapped=true)]
    public partial class startWorkResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string @return;
        
        public startWorkResponse() {
        }
        
        public startWorkResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="stopWork", WrapperNamespace="", IsWrapped=true)]
    public partial class stopWorkRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string id;
        
        public stopWorkRequest() {
        }
        
        public stopWorkRequest(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="stopWorkResponse", WrapperNamespace="", IsWrapped=true)]
    public partial class stopWorkResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string @return;
        
        public stopWorkResponse() {
        }
        
        public stopWorkResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pauseWork", WrapperNamespace="", IsWrapped=true)]
    public partial class pauseWorkRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string id;
        
        public pauseWorkRequest() {
        }
        
        public pauseWorkRequest(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pauseWorkResponse", WrapperNamespace="", IsWrapped=true)]
    public partial class pauseWorkResponse {
        
        public pauseWorkResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="stopPauseWork", WrapperNamespace="", IsWrapped=true)]
    public partial class stopPauseWorkRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string id;
        
        public stopPauseWorkRequest() {
        }
        
        public stopPauseWorkRequest(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="stopPauseWorkResponse", WrapperNamespace="", IsWrapped=true)]
    public partial class stopPauseWorkResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string @return;
        
        public stopPauseWorkResponse() {
        }
        
        public stopPauseWorkResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface zeiterfassungPortTypeChannel : WpfApplication3.ServiceReference1.zeiterfassungPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class zeiterfassungPortTypeClient : System.ServiceModel.ClientBase<WpfApplication3.ServiceReference1.zeiterfassungPortType>, WpfApplication3.ServiceReference1.zeiterfassungPortType {
        
        public zeiterfassungPortTypeClient() {
        }
        
        public zeiterfassungPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public zeiterfassungPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public zeiterfassungPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public zeiterfassungPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfApplication3.ServiceReference1.checkAuthentificationResponse WpfApplication3.ServiceReference1.zeiterfassungPortType.checkAuthentification(WpfApplication3.ServiceReference1.checkAuthentificationRequest request) {
            return base.Channel.checkAuthentification(request);
        }
        
        public bool checkAuthentification(string persnr, int pin) {
            WpfApplication3.ServiceReference1.checkAuthentificationRequest inValue = new WpfApplication3.ServiceReference1.checkAuthentificationRequest();
            inValue.persnr = persnr;
            inValue.pin = pin;
            WpfApplication3.ServiceReference1.checkAuthentificationResponse retVal = ((WpfApplication3.ServiceReference1.zeiterfassungPortType)(this)).checkAuthentification(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.checkAuthentificationResponse> WpfApplication3.ServiceReference1.zeiterfassungPortType.checkAuthentificationAsync(WpfApplication3.ServiceReference1.checkAuthentificationRequest request) {
            return base.Channel.checkAuthentificationAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.checkAuthentificationResponse> checkAuthentificationAsync(string persnr, int pin) {
            WpfApplication3.ServiceReference1.checkAuthentificationRequest inValue = new WpfApplication3.ServiceReference1.checkAuthentificationRequest();
            inValue.persnr = persnr;
            inValue.pin = pin;
            return ((WpfApplication3.ServiceReference1.zeiterfassungPortType)(this)).checkAuthentificationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfApplication3.ServiceReference1.createprojectResponse WpfApplication3.ServiceReference1.zeiterfassungPortType.createproject(WpfApplication3.ServiceReference1.createprojectRequest request) {
            return base.Channel.createproject(request);
        }
        
        public int createproject(int idprojekt, string projektname, string projektbeschreibung, int status, int kundennr) {
            WpfApplication3.ServiceReference1.createprojectRequest inValue = new WpfApplication3.ServiceReference1.createprojectRequest();
            inValue.idprojekt = idprojekt;
            inValue.projektname = projektname;
            inValue.projektbeschreibung = projektbeschreibung;
            inValue.status = status;
            inValue.kundennr = kundennr;
            WpfApplication3.ServiceReference1.createprojectResponse retVal = ((WpfApplication3.ServiceReference1.zeiterfassungPortType)(this)).createproject(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.createprojectResponse> WpfApplication3.ServiceReference1.zeiterfassungPortType.createprojectAsync(WpfApplication3.ServiceReference1.createprojectRequest request) {
            return base.Channel.createprojectAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.createprojectResponse> createprojectAsync(int idprojekt, string projektname, string projektbeschreibung, int status, int kundennr) {
            WpfApplication3.ServiceReference1.createprojectRequest inValue = new WpfApplication3.ServiceReference1.createprojectRequest();
            inValue.idprojekt = idprojekt;
            inValue.projektname = projektname;
            inValue.projektbeschreibung = projektbeschreibung;
            inValue.status = status;
            inValue.kundennr = kundennr;
            return ((WpfApplication3.ServiceReference1.zeiterfassungPortType)(this)).createprojectAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfApplication3.ServiceReference1.selectedcustomerResponse WpfApplication3.ServiceReference1.zeiterfassungPortType.selectedcustomer(WpfApplication3.ServiceReference1.selectedcustomerRequest request) {
            return base.Channel.selectedcustomer(request);
        }
        
        public int selectedcustomer(string Firmenname) {
            WpfApplication3.ServiceReference1.selectedcustomerRequest inValue = new WpfApplication3.ServiceReference1.selectedcustomerRequest();
            inValue.Firmenname = Firmenname;
            WpfApplication3.ServiceReference1.selectedcustomerResponse retVal = ((WpfApplication3.ServiceReference1.zeiterfassungPortType)(this)).selectedcustomer(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.selectedcustomerResponse> WpfApplication3.ServiceReference1.zeiterfassungPortType.selectedcustomerAsync(WpfApplication3.ServiceReference1.selectedcustomerRequest request) {
            return base.Channel.selectedcustomerAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.selectedcustomerResponse> selectedcustomerAsync(string Firmenname) {
            WpfApplication3.ServiceReference1.selectedcustomerRequest inValue = new WpfApplication3.ServiceReference1.selectedcustomerRequest();
            inValue.Firmenname = Firmenname;
            return ((WpfApplication3.ServiceReference1.zeiterfassungPortType)(this)).selectedcustomerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfApplication3.ServiceReference1.createcustomerResponse WpfApplication3.ServiceReference1.zeiterfassungPortType.createcustomer(WpfApplication3.ServiceReference1.createcustomerRequest request) {
            return base.Channel.createcustomer(request);
        }
        
        public int createcustomer(int KundenNr, string Nachname, string Vorname, string Firmenname, string TelNrMobil, string TelNrFestnetz, string EMail, int Status) {
            WpfApplication3.ServiceReference1.createcustomerRequest inValue = new WpfApplication3.ServiceReference1.createcustomerRequest();
            inValue.KundenNr = KundenNr;
            inValue.Nachname = Nachname;
            inValue.Vorname = Vorname;
            inValue.Firmenname = Firmenname;
            inValue.TelNrMobil = TelNrMobil;
            inValue.TelNrFestnetz = TelNrFestnetz;
            inValue.EMail = EMail;
            inValue.Status = Status;
            WpfApplication3.ServiceReference1.createcustomerResponse retVal = ((WpfApplication3.ServiceReference1.zeiterfassungPortType)(this)).createcustomer(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.createcustomerResponse> WpfApplication3.ServiceReference1.zeiterfassungPortType.createcustomerAsync(WpfApplication3.ServiceReference1.createcustomerRequest request) {
            return base.Channel.createcustomerAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.createcustomerResponse> createcustomerAsync(int KundenNr, string Nachname, string Vorname, string Firmenname, string TelNrMobil, string TelNrFestnetz, string EMail, int Status) {
            WpfApplication3.ServiceReference1.createcustomerRequest inValue = new WpfApplication3.ServiceReference1.createcustomerRequest();
            inValue.KundenNr = KundenNr;
            inValue.Nachname = Nachname;
            inValue.Vorname = Vorname;
            inValue.Firmenname = Firmenname;
            inValue.TelNrMobil = TelNrMobil;
            inValue.TelNrFestnetz = TelNrFestnetz;
            inValue.EMail = EMail;
            inValue.Status = Status;
            return ((WpfApplication3.ServiceReference1.zeiterfassungPortType)(this)).createcustomerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfApplication3.ServiceReference1.createemployeeResponse WpfApplication3.ServiceReference1.zeiterfassungPortType.createemployee(WpfApplication3.ServiceReference1.createemployeeRequest request) {
            return base.Channel.createemployee(request);
        }
        
        public int createemployee(int MitarbeiterNr, string Nachname, string Vorname, string Abteilung, System.DateTime Regelsarbeitszeit, System.DateTime GebTag, string TelNrMobil, string TelNrFestnetz, string EMail, int Berechtigungsstufe, int PIN, int Status) {
            WpfApplication3.ServiceReference1.createemployeeRequest inValue = new WpfApplication3.ServiceReference1.createemployeeRequest();
            inValue.MitarbeiterNr = MitarbeiterNr;
            inValue.Nachname = Nachname;
            inValue.Vorname = Vorname;
            inValue.Abteilung = Abteilung;
            inValue.Regelsarbeitszeit = Regelsarbeitszeit;
            inValue.GebTag = GebTag;
            inValue.TelNrMobil = TelNrMobil;
            inValue.TelNrFestnetz = TelNrFestnetz;
            inValue.EMail = EMail;
            inValue.Berechtigungsstufe = Berechtigungsstufe;
            inValue.PIN = PIN;
            inValue.Status = Status;
            WpfApplication3.ServiceReference1.createemployeeResponse retVal = ((WpfApplication3.ServiceReference1.zeiterfassungPortType)(this)).createemployee(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.createemployeeResponse> WpfApplication3.ServiceReference1.zeiterfassungPortType.createemployeeAsync(WpfApplication3.ServiceReference1.createemployeeRequest request) {
            return base.Channel.createemployeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.createemployeeResponse> createemployeeAsync(int MitarbeiterNr, string Nachname, string Vorname, string Abteilung, System.DateTime Regelsarbeitszeit, System.DateTime GebTag, string TelNrMobil, string TelNrFestnetz, string EMail, int Berechtigungsstufe, int PIN, int Status) {
            WpfApplication3.ServiceReference1.createemployeeRequest inValue = new WpfApplication3.ServiceReference1.createemployeeRequest();
            inValue.MitarbeiterNr = MitarbeiterNr;
            inValue.Nachname = Nachname;
            inValue.Vorname = Vorname;
            inValue.Abteilung = Abteilung;
            inValue.Regelsarbeitszeit = Regelsarbeitszeit;
            inValue.GebTag = GebTag;
            inValue.TelNrMobil = TelNrMobil;
            inValue.TelNrFestnetz = TelNrFestnetz;
            inValue.EMail = EMail;
            inValue.Berechtigungsstufe = Berechtigungsstufe;
            inValue.PIN = PIN;
            inValue.Status = Status;
            return ((WpfApplication3.ServiceReference1.zeiterfassungPortType)(this)).createemployeeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfApplication3.ServiceReference1.customerhasaddressResponse WpfApplication3.ServiceReference1.zeiterfassungPortType.customerhasaddress(WpfApplication3.ServiceReference1.customerhasaddressRequest request) {
            return base.Channel.customerhasaddress(request);
        }
        
        public bool customerhasaddress(int CustomerID, int AddressID) {
            WpfApplication3.ServiceReference1.customerhasaddressRequest inValue = new WpfApplication3.ServiceReference1.customerhasaddressRequest();
            inValue.CustomerID = CustomerID;
            inValue.AddressID = AddressID;
            WpfApplication3.ServiceReference1.customerhasaddressResponse retVal = ((WpfApplication3.ServiceReference1.zeiterfassungPortType)(this)).customerhasaddress(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.customerhasaddressResponse> WpfApplication3.ServiceReference1.zeiterfassungPortType.customerhasaddressAsync(WpfApplication3.ServiceReference1.customerhasaddressRequest request) {
            return base.Channel.customerhasaddressAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.customerhasaddressResponse> customerhasaddressAsync(int CustomerID, int AddressID) {
            WpfApplication3.ServiceReference1.customerhasaddressRequest inValue = new WpfApplication3.ServiceReference1.customerhasaddressRequest();
            inValue.CustomerID = CustomerID;
            inValue.AddressID = AddressID;
            return ((WpfApplication3.ServiceReference1.zeiterfassungPortType)(this)).customerhasaddressAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfApplication3.ServiceReference1.employeehasaddressResponse WpfApplication3.ServiceReference1.zeiterfassungPortType.employeehasaddress(WpfApplication3.ServiceReference1.employeehasaddressRequest request) {
            return base.Channel.employeehasaddress(request);
        }
        
        public bool employeehasaddress(int EmployeeID, int AddressID) {
            WpfApplication3.ServiceReference1.employeehasaddressRequest inValue = new WpfApplication3.ServiceReference1.employeehasaddressRequest();
            inValue.EmployeeID = EmployeeID;
            inValue.AddressID = AddressID;
            WpfApplication3.ServiceReference1.employeehasaddressResponse retVal = ((WpfApplication3.ServiceReference1.zeiterfassungPortType)(this)).employeehasaddress(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.employeehasaddressResponse> WpfApplication3.ServiceReference1.zeiterfassungPortType.employeehasaddressAsync(WpfApplication3.ServiceReference1.employeehasaddressRequest request) {
            return base.Channel.employeehasaddressAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.employeehasaddressResponse> employeehasaddressAsync(int EmployeeID, int AddressID) {
            WpfApplication3.ServiceReference1.employeehasaddressRequest inValue = new WpfApplication3.ServiceReference1.employeehasaddressRequest();
            inValue.EmployeeID = EmployeeID;
            inValue.AddressID = AddressID;
            return ((WpfApplication3.ServiceReference1.zeiterfassungPortType)(this)).employeehasaddressAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfApplication3.ServiceReference1.createaddressResponse WpfApplication3.ServiceReference1.zeiterfassungPortType.createaddress(WpfApplication3.ServiceReference1.createaddressRequest request) {
            return base.Channel.createaddress(request);
        }
        
        public int createaddress(string Ort, int PLZ, string Strasse, string Hausnummer, int Postfach) {
            WpfApplication3.ServiceReference1.createaddressRequest inValue = new WpfApplication3.ServiceReference1.createaddressRequest();
            inValue.Ort = Ort;
            inValue.PLZ = PLZ;
            inValue.Strasse = Strasse;
            inValue.Hausnummer = Hausnummer;
            inValue.Postfach = Postfach;
            WpfApplication3.ServiceReference1.createaddressResponse retVal = ((WpfApplication3.ServiceReference1.zeiterfassungPortType)(this)).createaddress(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.createaddressResponse> WpfApplication3.ServiceReference1.zeiterfassungPortType.createaddressAsync(WpfApplication3.ServiceReference1.createaddressRequest request) {
            return base.Channel.createaddressAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.createaddressResponse> createaddressAsync(string Ort, int PLZ, string Strasse, string Hausnummer, int Postfach) {
            WpfApplication3.ServiceReference1.createaddressRequest inValue = new WpfApplication3.ServiceReference1.createaddressRequest();
            inValue.Ort = Ort;
            inValue.PLZ = PLZ;
            inValue.Strasse = Strasse;
            inValue.Hausnummer = Hausnummer;
            inValue.Postfach = Postfach;
            return ((WpfApplication3.ServiceReference1.zeiterfassungPortType)(this)).createaddressAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfApplication3.ServiceReference1.startWorkResponse WpfApplication3.ServiceReference1.zeiterfassungPortType.startWork(WpfApplication3.ServiceReference1.startWorkRequest request) {
            return base.Channel.startWork(request);
        }
        
        public string startWork(string project, string activity) {
            WpfApplication3.ServiceReference1.startWorkRequest inValue = new WpfApplication3.ServiceReference1.startWorkRequest();
            inValue.project = project;
            inValue.activity = activity;
            WpfApplication3.ServiceReference1.startWorkResponse retVal = ((WpfApplication3.ServiceReference1.zeiterfassungPortType)(this)).startWork(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.startWorkResponse> WpfApplication3.ServiceReference1.zeiterfassungPortType.startWorkAsync(WpfApplication3.ServiceReference1.startWorkRequest request) {
            return base.Channel.startWorkAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.startWorkResponse> startWorkAsync(string project, string activity) {
            WpfApplication3.ServiceReference1.startWorkRequest inValue = new WpfApplication3.ServiceReference1.startWorkRequest();
            inValue.project = project;
            inValue.activity = activity;
            return ((WpfApplication3.ServiceReference1.zeiterfassungPortType)(this)).startWorkAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfApplication3.ServiceReference1.stopWorkResponse WpfApplication3.ServiceReference1.zeiterfassungPortType.stopWork(WpfApplication3.ServiceReference1.stopWorkRequest request) {
            return base.Channel.stopWork(request);
        }
        
        public string stopWork(string id) {
            WpfApplication3.ServiceReference1.stopWorkRequest inValue = new WpfApplication3.ServiceReference1.stopWorkRequest();
            inValue.id = id;
            WpfApplication3.ServiceReference1.stopWorkResponse retVal = ((WpfApplication3.ServiceReference1.zeiterfassungPortType)(this)).stopWork(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.stopWorkResponse> WpfApplication3.ServiceReference1.zeiterfassungPortType.stopWorkAsync(WpfApplication3.ServiceReference1.stopWorkRequest request) {
            return base.Channel.stopWorkAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.stopWorkResponse> stopWorkAsync(string id) {
            WpfApplication3.ServiceReference1.stopWorkRequest inValue = new WpfApplication3.ServiceReference1.stopWorkRequest();
            inValue.id = id;
            return ((WpfApplication3.ServiceReference1.zeiterfassungPortType)(this)).stopWorkAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfApplication3.ServiceReference1.pauseWorkResponse WpfApplication3.ServiceReference1.zeiterfassungPortType.pauseWork(WpfApplication3.ServiceReference1.pauseWorkRequest request) {
            return base.Channel.pauseWork(request);
        }
        
        public void pauseWork(string id) {
            WpfApplication3.ServiceReference1.pauseWorkRequest inValue = new WpfApplication3.ServiceReference1.pauseWorkRequest();
            inValue.id = id;
            WpfApplication3.ServiceReference1.pauseWorkResponse retVal = ((WpfApplication3.ServiceReference1.zeiterfassungPortType)(this)).pauseWork(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.pauseWorkResponse> WpfApplication3.ServiceReference1.zeiterfassungPortType.pauseWorkAsync(WpfApplication3.ServiceReference1.pauseWorkRequest request) {
            return base.Channel.pauseWorkAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.pauseWorkResponse> pauseWorkAsync(string id) {
            WpfApplication3.ServiceReference1.pauseWorkRequest inValue = new WpfApplication3.ServiceReference1.pauseWorkRequest();
            inValue.id = id;
            return ((WpfApplication3.ServiceReference1.zeiterfassungPortType)(this)).pauseWorkAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfApplication3.ServiceReference1.stopPauseWorkResponse WpfApplication3.ServiceReference1.zeiterfassungPortType.stopPauseWork(WpfApplication3.ServiceReference1.stopPauseWorkRequest request) {
            return base.Channel.stopPauseWork(request);
        }
        
        public string stopPauseWork(string id) {
            WpfApplication3.ServiceReference1.stopPauseWorkRequest inValue = new WpfApplication3.ServiceReference1.stopPauseWorkRequest();
            inValue.id = id;
            WpfApplication3.ServiceReference1.stopPauseWorkResponse retVal = ((WpfApplication3.ServiceReference1.zeiterfassungPortType)(this)).stopPauseWork(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.stopPauseWorkResponse> WpfApplication3.ServiceReference1.zeiterfassungPortType.stopPauseWorkAsync(WpfApplication3.ServiceReference1.stopPauseWorkRequest request) {
            return base.Channel.stopPauseWorkAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfApplication3.ServiceReference1.stopPauseWorkResponse> stopPauseWorkAsync(string id) {
            WpfApplication3.ServiceReference1.stopPauseWorkRequest inValue = new WpfApplication3.ServiceReference1.stopPauseWorkRequest();
            inValue.id = id;
            return ((WpfApplication3.ServiceReference1.zeiterfassungPortType)(this)).stopPauseWorkAsync(inValue);
        }
        
        public string[] loadprojects() {
            return base.Channel.loadprojects();
        }
        
        public System.Threading.Tasks.Task<string[]> loadprojectsAsync() {
            return base.Channel.loadprojectsAsync();
        }
        
        public string[] loadcustomers() {
            return base.Channel.loadcustomers();
        }
        
        public System.Threading.Tasks.Task<string[]> loadcustomersAsync() {
            return base.Channel.loadcustomersAsync();
        }
        
        public string[] loadactivities() {
            return base.Channel.loadactivities();
        }
        
        public System.Threading.Tasks.Task<string[]> loadactivitiesAsync() {
            return base.Channel.loadactivitiesAsync();
        }
        
        public string[] loadauthorisations() {
            return base.Channel.loadauthorisations();
        }
        
        public System.Threading.Tasks.Task<string[]> loadauthorisationsAsync() {
            return base.Channel.loadauthorisationsAsync();
        }
    }
}
